// Generated by @opencode-ai/httpapi-codegen. Do not edit.
import { Effect, Stream, Schema } from "effect"
import { Sse } from "effect/unstable/encoding"
import { HttpClientError } from "effect/unstable/http"
import { HttpApiClient } from "effect/unstable/httpapi"
import { ClientApi } from "../contract"
import { ClientError } from "./client-error"

type RawClient = HttpApiClient.ForApi<typeof ClientApi>

const mapClientError = <E>(error: E) =>
  HttpClientError.isHttpClientError(error) || Schema.isSchemaError(error) || Sse.Retry.is(error)
    ? new ClientError({ cause: error })
    : error

const Endpoint0_0 = (raw: RawClient["server.health"]) => () =>
  raw["health.get"]({}).pipe(Effect.mapError(mapClientError))

const adaptGroup0 = (raw: RawClient["server.health"]) => ({ get: Endpoint0_0(raw) })

type Endpoint1_0Request = Parameters<RawClient["server.location"]["location.get"]>[0]
type Endpoint1_0Input = { readonly location?: Endpoint1_0Request["query"]["location"] }
const Endpoint1_0 = (raw: RawClient["server.location"]) => (input?: Endpoint1_0Input) =>
  raw["location.get"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint1_1Request = Parameters<RawClient["server.location"]["location.dispose"]>[0]
type Endpoint1_1Input = { readonly location?: Endpoint1_1Request["query"]["location"] }
const Endpoint1_1 = (raw: RawClient["server.location"]) => (input?: Endpoint1_1Input) =>
  raw["location.dispose"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

const adaptGroup1 = (raw: RawClient["server.location"]) => ({ get: Endpoint1_0(raw), dispose: Endpoint1_1(raw) })

type Endpoint2_0Request = Parameters<RawClient["server.path"]["path.get"]>[0]
type Endpoint2_0Input = { readonly location?: Endpoint2_0Request["query"]["location"] }
const Endpoint2_0 = (raw: RawClient["server.path"]) => (input?: Endpoint2_0Input) =>
  raw["path.get"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

const adaptGroup2 = (raw: RawClient["server.path"]) => ({ get: Endpoint2_0(raw) })

type Endpoint3_0Request = Parameters<RawClient["server.agent"]["agent.list"]>[0]
type Endpoint3_0Input = { readonly location?: Endpoint3_0Request["query"]["location"] }
const Endpoint3_0 = (raw: RawClient["server.agent"]) => (input?: Endpoint3_0Input) =>
  raw["agent.list"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

const adaptGroup3 = (raw: RawClient["server.agent"]) => ({ list: Endpoint3_0(raw) })

type Endpoint4_0Request = Parameters<RawClient["server.session"]["session.list"]>[0]
type Endpoint4_0Input = {
  readonly workspace?: Endpoint4_0Request["query"]["workspace"]
  readonly limit?: Endpoint4_0Request["query"]["limit"]
  readonly order?: Endpoint4_0Request["query"]["order"]
  readonly search?: Endpoint4_0Request["query"]["search"]
  readonly parentID?: Endpoint4_0Request["query"]["parentID"]
  readonly directory?: Endpoint4_0Request["query"]["directory"]
  readonly project?: Endpoint4_0Request["query"]["project"]
  readonly subpath?: Endpoint4_0Request["query"]["subpath"]
  readonly cursor?: Endpoint4_0Request["query"]["cursor"]
}
const Endpoint4_0 = (raw: RawClient["server.session"]) => (input?: Endpoint4_0Input) =>
  raw["session.list"]({
    query: {
      workspace: input?.["workspace"],
      limit: input?.["limit"],
      order: input?.["order"],
      search: input?.["search"],
      parentID: input?.["parentID"],
      directory: input?.["directory"],
      project: input?.["project"],
      subpath: input?.["subpath"],
      cursor: input?.["cursor"],
    },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint4_1Request = Parameters<RawClient["server.session"]["session.create"]>[0]
type Endpoint4_1Input = {
  readonly id?: Endpoint4_1Request["payload"]["id"]
  readonly agent?: Endpoint4_1Request["payload"]["agent"]
  readonly model?: Endpoint4_1Request["payload"]["model"]
  readonly location?: Endpoint4_1Request["payload"]["location"]
}
const Endpoint4_1 = (raw: RawClient["server.session"]) => (input?: Endpoint4_1Input) =>
  raw["session.create"]({
    payload: { id: input?.["id"], agent: input?.["agent"], model: input?.["model"], location: input?.["location"] },
  }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

const Endpoint4_2 = (raw: RawClient["server.session"]) => () =>
  raw["session.active"]({}).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint4_3Request = Parameters<RawClient["server.session"]["session.get"]>[0]
type Endpoint4_3Input = { readonly sessionID: Endpoint4_3Request["params"]["sessionID"] }
const Endpoint4_3 = (raw: RawClient["server.session"]) => (input: Endpoint4_3Input) =>
  raw["session.get"]({ params: { sessionID: input["sessionID"] } }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint4_4Request = Parameters<RawClient["server.session"]["session.children"]>[0]
type Endpoint4_4Input = { readonly sessionID: Endpoint4_4Request["params"]["sessionID"] }
const Endpoint4_4 = (raw: RawClient["server.session"]) => (input: Endpoint4_4Input) =>
  raw["session.children"]({ params: { sessionID: input["sessionID"] } }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint4_5Request = Parameters<RawClient["server.session"]["session.todo"]>[0]
type Endpoint4_5Input = { readonly sessionID: Endpoint4_5Request["params"]["sessionID"] }
const Endpoint4_5 = (raw: RawClient["server.session"]) => (input: Endpoint4_5Input) =>
  raw["session.todo"]({ params: { sessionID: input["sessionID"] } }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint4_6Request = Parameters<RawClient["server.session"]["session.fork"]>[0]
type Endpoint4_6Input = {
  readonly sessionID: Endpoint4_6Request["params"]["sessionID"]
  readonly messageID?: Endpoint4_6Request["payload"]["messageID"]
}
const Endpoint4_6 = (raw: RawClient["server.session"]) => (input: Endpoint4_6Input) =>
  raw["session.fork"]({ params: { sessionID: input["sessionID"] }, payload: { messageID: input["messageID"] } }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint4_7Request = Parameters<RawClient["server.session"]["session.update"]>[0]
type Endpoint4_7Input = {
  readonly sessionID: Endpoint4_7Request["params"]["sessionID"]
  readonly title?: Endpoint4_7Request["payload"]["title"]
  readonly archived?: Endpoint4_7Request["payload"]["archived"]
}
const Endpoint4_7 = (raw: RawClient["server.session"]) => (input: Endpoint4_7Input) =>
  raw["session.update"]({
    params: { sessionID: input["sessionID"] },
    payload: { title: input["title"], archived: input["archived"] },
  }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint4_8Request = Parameters<RawClient["server.session"]["session.remove"]>[0]
type Endpoint4_8Input = { readonly sessionID: Endpoint4_8Request["params"]["sessionID"] }
const Endpoint4_8 = (raw: RawClient["server.session"]) => (input: Endpoint4_8Input) =>
  raw["session.remove"]({ params: { sessionID: input["sessionID"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint4_9Request = Parameters<RawClient["server.session"]["session.share"]>[0]
type Endpoint4_9Input = { readonly sessionID: Endpoint4_9Request["params"]["sessionID"] }
const Endpoint4_9 = (raw: RawClient["server.session"]) => (input: Endpoint4_9Input) =>
  raw["session.share"]({ params: { sessionID: input["sessionID"] } }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint4_10Request = Parameters<RawClient["server.session"]["session.unshare"]>[0]
type Endpoint4_10Input = { readonly sessionID: Endpoint4_10Request["params"]["sessionID"] }
const Endpoint4_10 = (raw: RawClient["server.session"]) => (input: Endpoint4_10Input) =>
  raw["session.unshare"]({ params: { sessionID: input["sessionID"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint4_11Request = Parameters<RawClient["server.session"]["session.switchAgent"]>[0]
type Endpoint4_11Input = {
  readonly sessionID: Endpoint4_11Request["params"]["sessionID"]
  readonly agent: Endpoint4_11Request["payload"]["agent"]
}
const Endpoint4_11 = (raw: RawClient["server.session"]) => (input: Endpoint4_11Input) =>
  raw["session.switchAgent"]({ params: { sessionID: input["sessionID"] }, payload: { agent: input["agent"] } }).pipe(
    Effect.mapError(mapClientError),
  )

type Endpoint4_12Request = Parameters<RawClient["server.session"]["session.switchModel"]>[0]
type Endpoint4_12Input = {
  readonly sessionID: Endpoint4_12Request["params"]["sessionID"]
  readonly model: Endpoint4_12Request["payload"]["model"]
}
const Endpoint4_12 = (raw: RawClient["server.session"]) => (input: Endpoint4_12Input) =>
  raw["session.switchModel"]({ params: { sessionID: input["sessionID"] }, payload: { model: input["model"] } }).pipe(
    Effect.mapError(mapClientError),
  )

type Endpoint4_13Request = Parameters<RawClient["server.session"]["session.prompt"]>[0]
type Endpoint4_13Input = {
  readonly sessionID: Endpoint4_13Request["params"]["sessionID"]
  readonly id?: Endpoint4_13Request["payload"]["id"]
  readonly prompt: Endpoint4_13Request["payload"]["prompt"]
  readonly model?: Endpoint4_13Request["payload"]["model"]
  readonly delivery?: Endpoint4_13Request["payload"]["delivery"]
  readonly expectedActiveAttemptID?: Endpoint4_13Request["payload"]["expectedActiveAttemptID"]
  readonly resume?: Endpoint4_13Request["payload"]["resume"]
}
const Endpoint4_13 = (raw: RawClient["server.session"]) => (input: Endpoint4_13Input) =>
  raw["session.prompt"]({
    params: { sessionID: input["sessionID"] },
    payload: {
      id: input["id"],
      prompt: input["prompt"],
      model: input["model"],
      delivery: input["delivery"],
      expectedActiveAttemptID: input["expectedActiveAttemptID"],
      resume: input["resume"],
    },
  }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint4_14Request = Parameters<RawClient["server.session"]["session.diff"]>[0]
type Endpoint4_14Input = {
  readonly sessionID: Endpoint4_14Request["params"]["sessionID"]
  readonly messageID?: Endpoint4_14Request["query"]["messageID"]
}
const Endpoint4_14 = (raw: RawClient["server.session"]) => (input: Endpoint4_14Input) =>
  raw["session.diff"]({ params: { sessionID: input["sessionID"] }, query: { messageID: input["messageID"] } }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint4_15Request = Parameters<RawClient["server.session"]["session.input.list"]>[0]
type Endpoint4_15Input = {
  readonly sessionID: Endpoint4_15Request["params"]["sessionID"]
  readonly delivery?: Endpoint4_15Request["query"]["delivery"]
}
const Endpoint4_15 = (raw: RawClient["server.session"]) => (input: Endpoint4_15Input) =>
  raw["session.input.list"]({ params: { sessionID: input["sessionID"] }, query: { delivery: input["delivery"] } }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint4_16Request = Parameters<RawClient["server.session"]["session.input.get"]>[0]
type Endpoint4_16Input = {
  readonly sessionID: Endpoint4_16Request["params"]["sessionID"]
  readonly inputID: Endpoint4_16Request["params"]["inputID"]
}
const Endpoint4_16 = (raw: RawClient["server.session"]) => (input: Endpoint4_16Input) =>
  raw["session.input.get"]({ params: { sessionID: input["sessionID"], inputID: input["inputID"] } }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint4_17Request = Parameters<RawClient["server.session"]["session.input.promote"]>[0]
type Endpoint4_17Input = {
  readonly sessionID: Endpoint4_17Request["params"]["sessionID"]
  readonly inputID: Endpoint4_17Request["params"]["inputID"]
}
const Endpoint4_17 = (raw: RawClient["server.session"]) => (input: Endpoint4_17Input) =>
  raw["session.input.promote"]({ params: { sessionID: input["sessionID"], inputID: input["inputID"] } }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint4_18Request = Parameters<RawClient["server.session"]["session.input.cancel"]>[0]
type Endpoint4_18Input = {
  readonly sessionID: Endpoint4_18Request["params"]["sessionID"]
  readonly inputID: Endpoint4_18Request["params"]["inputID"]
}
const Endpoint4_18 = (raw: RawClient["server.session"]) => (input: Endpoint4_18Input) =>
  raw["session.input.cancel"]({ params: { sessionID: input["sessionID"], inputID: input["inputID"] } }).pipe(
    Effect.mapError(mapClientError),
  )

type Endpoint4_19Request = Parameters<RawClient["server.session"]["session.background"]>[0]
type Endpoint4_19Input = { readonly sessionID: Endpoint4_19Request["params"]["sessionID"] }
const Endpoint4_19 = (raw: RawClient["server.session"]) => (input: Endpoint4_19Input) =>
  raw["session.background"]({ params: { sessionID: input["sessionID"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint4_20Request = Parameters<RawClient["server.session"]["session.command"]>[0]
type Endpoint4_20Input = {
  readonly sessionID: Endpoint4_20Request["params"]["sessionID"]
  readonly id?: Endpoint4_20Request["payload"]["id"]
  readonly command: Endpoint4_20Request["payload"]["command"]
  readonly arguments: Endpoint4_20Request["payload"]["arguments"]
  readonly agent?: Endpoint4_20Request["payload"]["agent"]
  readonly model?: Endpoint4_20Request["payload"]["model"]
  readonly files?: Endpoint4_20Request["payload"]["files"]
  readonly delivery?: Endpoint4_20Request["payload"]["delivery"]
  readonly expectedActiveAttemptID?: Endpoint4_20Request["payload"]["expectedActiveAttemptID"]
  readonly resume?: Endpoint4_20Request["payload"]["resume"]
  readonly commit?: Endpoint4_20Request["payload"]["commit"]
}
const Endpoint4_20 = (raw: RawClient["server.session"]) => (input: Endpoint4_20Input) =>
  raw["session.command"]({
    params: { sessionID: input["sessionID"] },
    payload: {
      id: input["id"],
      command: input["command"],
      arguments: input["arguments"],
      agent: input["agent"],
      model: input["model"],
      files: input["files"],
      delivery: input["delivery"],
      expectedActiveAttemptID: input["expectedActiveAttemptID"],
      resume: input["resume"],
      commit: input["commit"],
    },
  }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint4_21Request = Parameters<RawClient["server.session"]["session.shell"]>[0]
type Endpoint4_21Input = {
  readonly sessionID: Endpoint4_21Request["params"]["sessionID"]
  readonly id?: Endpoint4_21Request["payload"]["id"]
  readonly userID?: Endpoint4_21Request["payload"]["userID"]
  readonly command: Endpoint4_21Request["payload"]["command"]
  readonly agent?: Endpoint4_21Request["payload"]["agent"]
  readonly model?: Endpoint4_21Request["payload"]["model"]
  readonly resume?: Endpoint4_21Request["payload"]["resume"]
}
const Endpoint4_21 = (raw: RawClient["server.session"]) => (input: Endpoint4_21Input) =>
  raw["session.shell"]({
    params: { sessionID: input["sessionID"] },
    payload: {
      id: input["id"],
      userID: input["userID"],
      command: input["command"],
      agent: input["agent"],
      model: input["model"],
      resume: input["resume"],
    },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint4_22Request = Parameters<RawClient["server.session"]["session.compact"]>[0]
type Endpoint4_22Input = { readonly sessionID: Endpoint4_22Request["params"]["sessionID"] }
const Endpoint4_22 = (raw: RawClient["server.session"]) => (input: Endpoint4_22Input) =>
  raw["session.compact"]({ params: { sessionID: input["sessionID"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint4_23Request = Parameters<RawClient["server.session"]["session.wait"]>[0]
type Endpoint4_23Input = { readonly sessionID: Endpoint4_23Request["params"]["sessionID"] }
const Endpoint4_23 = (raw: RawClient["server.session"]) => (input: Endpoint4_23Input) =>
  raw["session.wait"]({ params: { sessionID: input["sessionID"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint4_24Request = Parameters<RawClient["server.session"]["session.revert.stage"]>[0]
type Endpoint4_24Input = {
  readonly sessionID: Endpoint4_24Request["params"]["sessionID"]
  readonly messageID: Endpoint4_24Request["payload"]["messageID"]
  readonly files?: Endpoint4_24Request["payload"]["files"]
}
const Endpoint4_24 = (raw: RawClient["server.session"]) => (input: Endpoint4_24Input) =>
  raw["session.revert.stage"]({
    params: { sessionID: input["sessionID"] },
    payload: { messageID: input["messageID"], files: input["files"] },
  }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint4_25Request = Parameters<RawClient["server.session"]["session.revert.clear"]>[0]
type Endpoint4_25Input = { readonly sessionID: Endpoint4_25Request["params"]["sessionID"] }
const Endpoint4_25 = (raw: RawClient["server.session"]) => (input: Endpoint4_25Input) =>
  raw["session.revert.clear"]({ params: { sessionID: input["sessionID"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint4_26Request = Parameters<RawClient["server.session"]["session.revert.commit"]>[0]
type Endpoint4_26Input = { readonly sessionID: Endpoint4_26Request["params"]["sessionID"] }
const Endpoint4_26 = (raw: RawClient["server.session"]) => (input: Endpoint4_26Input) =>
  raw["session.revert.commit"]({ params: { sessionID: input["sessionID"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint4_27Request = Parameters<RawClient["server.session"]["session.context"]>[0]
type Endpoint4_27Input = { readonly sessionID: Endpoint4_27Request["params"]["sessionID"] }
const Endpoint4_27 = (raw: RawClient["server.session"]) => (input: Endpoint4_27Input) =>
  raw["session.context"]({ params: { sessionID: input["sessionID"] } }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint4_28Request = Parameters<RawClient["server.session"]["session.history"]>[0]
type Endpoint4_28Input = {
  readonly sessionID: Endpoint4_28Request["params"]["sessionID"]
  readonly limit?: Endpoint4_28Request["query"]["limit"]
  readonly after?: Endpoint4_28Request["query"]["after"]
}
const Endpoint4_28 = (raw: RawClient["server.session"]) => (input: Endpoint4_28Input) =>
  raw["session.history"]({
    params: { sessionID: input["sessionID"] },
    query: { limit: input["limit"], after: input["after"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint4_29Request = Parameters<RawClient["server.session"]["session.events"]>[0]
type Endpoint4_29Input = {
  readonly sessionID: Endpoint4_29Request["params"]["sessionID"]
  readonly after?: Endpoint4_29Request["query"]["after"]
}
const Endpoint4_29 = (raw: RawClient["server.session"]) => (input: Endpoint4_29Input) =>
  Stream.unwrap(
    raw["session.events"]({ params: { sessionID: input["sessionID"] }, query: { after: input["after"] } }).pipe(
      Effect.mapError(mapClientError),
      Effect.map((stream) => stream.pipe(Stream.mapError(mapClientError))),
    ),
  )

type Endpoint4_30Request = Parameters<RawClient["server.session"]["session.interrupt"]>[0]
type Endpoint4_30Input = { readonly sessionID: Endpoint4_30Request["params"]["sessionID"] }
const Endpoint4_30 = (raw: RawClient["server.session"]) => (input: Endpoint4_30Input) =>
  raw["session.interrupt"]({ params: { sessionID: input["sessionID"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint4_31Request = Parameters<RawClient["server.session"]["session.message"]>[0]
type Endpoint4_31Input = {
  readonly sessionID: Endpoint4_31Request["params"]["sessionID"]
  readonly messageID: Endpoint4_31Request["params"]["messageID"]
}
const Endpoint4_31 = (raw: RawClient["server.session"]) => (input: Endpoint4_31Input) =>
  raw["session.message"]({ params: { sessionID: input["sessionID"], messageID: input["messageID"] } }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

const adaptGroup4 = (raw: RawClient["server.session"]) => ({
  list: Endpoint4_0(raw),
  create: Endpoint4_1(raw),
  active: Endpoint4_2(raw),
  get: Endpoint4_3(raw),
  children: Endpoint4_4(raw),
  todo: Endpoint4_5(raw),
  fork: Endpoint4_6(raw),
  update: Endpoint4_7(raw),
  remove: Endpoint4_8(raw),
  share: Endpoint4_9(raw),
  unshare: Endpoint4_10(raw),
  switchAgent: Endpoint4_11(raw),
  switchModel: Endpoint4_12(raw),
  prompt: Endpoint4_13(raw),
  diff: Endpoint4_14(raw),
  inputList: Endpoint4_15(raw),
  inputGet: Endpoint4_16(raw),
  inputPromote: Endpoint4_17(raw),
  inputCancel: Endpoint4_18(raw),
  background: Endpoint4_19(raw),
  command: Endpoint4_20(raw),
  shell: Endpoint4_21(raw),
  compact: Endpoint4_22(raw),
  wait: Endpoint4_23(raw),
  stage: Endpoint4_24(raw),
  clear: Endpoint4_25(raw),
  commit: Endpoint4_26(raw),
  context: Endpoint4_27(raw),
  history: Endpoint4_28(raw),
  events: Endpoint4_29(raw),
  interrupt: Endpoint4_30(raw),
  message: Endpoint4_31(raw),
})

type Endpoint5_0Request = Parameters<RawClient["server.message"]["session.messages"]>[0]
type Endpoint5_0Input = {
  readonly sessionID: Endpoint5_0Request["params"]["sessionID"]
  readonly limit?: Endpoint5_0Request["query"]["limit"]
  readonly order?: Endpoint5_0Request["query"]["order"]
  readonly cursor?: Endpoint5_0Request["query"]["cursor"]
}
const Endpoint5_0 = (raw: RawClient["server.message"]) => (input: Endpoint5_0Input) =>
  raw["session.messages"]({
    params: { sessionID: input["sessionID"] },
    query: { limit: input["limit"], order: input["order"], cursor: input["cursor"] },
  }).pipe(Effect.mapError(mapClientError))

const adaptGroup5 = (raw: RawClient["server.message"]) => ({ list: Endpoint5_0(raw) })

type Endpoint6_0Request = Parameters<RawClient["server.model"]["model.list"]>[0]
type Endpoint6_0Input = { readonly location?: Endpoint6_0Request["query"]["location"] }
const Endpoint6_0 = (raw: RawClient["server.model"]) => (input?: Endpoint6_0Input) =>
  raw["model.list"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

const adaptGroup6 = (raw: RawClient["server.model"]) => ({ list: Endpoint6_0(raw) })

type Endpoint7_0Request = Parameters<RawClient["server.provider"]["provider.catalog"]>[0]
type Endpoint7_0Input = { readonly location?: Endpoint7_0Request["query"]["location"] }
const Endpoint7_0 = (raw: RawClient["server.provider"]) => (input?: Endpoint7_0Input) =>
  raw["provider.catalog"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint7_1Request = Parameters<RawClient["server.provider"]["provider.list"]>[0]
type Endpoint7_1Input = { readonly location?: Endpoint7_1Request["query"]["location"] }
const Endpoint7_1 = (raw: RawClient["server.provider"]) => (input?: Endpoint7_1Input) =>
  raw["provider.list"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint7_2Request = Parameters<RawClient["server.provider"]["provider.get"]>[0]
type Endpoint7_2Input = {
  readonly providerID: Endpoint7_2Request["params"]["providerID"]
  readonly location?: Endpoint7_2Request["query"]["location"]
}
const Endpoint7_2 = (raw: RawClient["server.provider"]) => (input: Endpoint7_2Input) =>
  raw["provider.get"]({ params: { providerID: input["providerID"] }, query: { location: input["location"] } }).pipe(
    Effect.mapError(mapClientError),
  )

type Endpoint7_3Request = Parameters<RawClient["server.provider"]["provider.custom.discover"]>[0]
type Endpoint7_3Input = {
  readonly location?: Endpoint7_3Request["query"]["location"]
  readonly protocol?: Endpoint7_3Request["payload"]["protocol"]
  readonly baseURL: Endpoint7_3Request["payload"]["baseURL"]
  readonly apiKey?: Endpoint7_3Request["payload"]["apiKey"]
  readonly headers: Endpoint7_3Request["payload"]["headers"]
}
const Endpoint7_3 = (raw: RawClient["server.provider"]) => (input: Endpoint7_3Input) =>
  raw["provider.custom.discover"]({
    query: { location: input["location"] },
    payload: {
      protocol: input["protocol"],
      baseURL: input["baseURL"],
      apiKey: input["apiKey"],
      headers: input["headers"],
    },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint7_4Request = Parameters<RawClient["server.provider"]["provider.custom.configure"]>[0]
type Endpoint7_4Input = {
  readonly location?: Endpoint7_4Request["query"]["location"]
  readonly providerID: Endpoint7_4Request["payload"]["providerID"]
  readonly name: Endpoint7_4Request["payload"]["name"]
  readonly protocol?: Endpoint7_4Request["payload"]["protocol"]
  readonly update?: Endpoint7_4Request["payload"]["update"]
  readonly baseURL: Endpoint7_4Request["payload"]["baseURL"]
  readonly apiKey?: Endpoint7_4Request["payload"]["apiKey"]
  readonly headers: Endpoint7_4Request["payload"]["headers"]
  readonly models: Endpoint7_4Request["payload"]["models"]
}
const Endpoint7_4 = (raw: RawClient["server.provider"]) => (input: Endpoint7_4Input) =>
  raw["provider.custom.configure"]({
    query: { location: input["location"] },
    payload: {
      providerID: input["providerID"],
      name: input["name"],
      protocol: input["protocol"],
      update: input["update"],
      baseURL: input["baseURL"],
      apiKey: input["apiKey"],
      headers: input["headers"],
      models: input["models"],
    },
  }).pipe(Effect.mapError(mapClientError))

const adaptGroup7 = (raw: RawClient["server.provider"]) => ({
  catalog: Endpoint7_0(raw),
  list: Endpoint7_1(raw),
  get: Endpoint7_2(raw),
  discoverCustom: Endpoint7_3(raw),
  configureCustom: Endpoint7_4(raw),
})

type Endpoint8_0Request = Parameters<RawClient["server.integration"]["integration.list"]>[0]
type Endpoint8_0Input = { readonly location?: Endpoint8_0Request["query"]["location"] }
const Endpoint8_0 = (raw: RawClient["server.integration"]) => (input?: Endpoint8_0Input) =>
  raw["integration.list"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint8_1Request = Parameters<RawClient["server.integration"]["integration.get"]>[0]
type Endpoint8_1Input = {
  readonly integrationID: Endpoint8_1Request["params"]["integrationID"]
  readonly location?: Endpoint8_1Request["query"]["location"]
}
const Endpoint8_1 = (raw: RawClient["server.integration"]) => (input: Endpoint8_1Input) =>
  raw["integration.get"]({
    params: { integrationID: input["integrationID"] },
    query: { location: input["location"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint8_2Request = Parameters<RawClient["server.integration"]["integration.connect.key"]>[0]
type Endpoint8_2Input = {
  readonly integrationID: Endpoint8_2Request["params"]["integrationID"]
  readonly location?: Endpoint8_2Request["query"]["location"]
  readonly key: Endpoint8_2Request["payload"]["key"]
  readonly label?: Endpoint8_2Request["payload"]["label"]
}
const Endpoint8_2 = (raw: RawClient["server.integration"]) => (input: Endpoint8_2Input) =>
  raw["integration.connect.key"]({
    params: { integrationID: input["integrationID"] },
    query: { location: input["location"] },
    payload: { key: input["key"], label: input["label"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint8_3Request = Parameters<RawClient["server.integration"]["integration.connect.oauth"]>[0]
type Endpoint8_3Input = {
  readonly integrationID: Endpoint8_3Request["params"]["integrationID"]
  readonly location?: Endpoint8_3Request["query"]["location"]
  readonly methodID: Endpoint8_3Request["payload"]["methodID"]
  readonly inputs: Endpoint8_3Request["payload"]["inputs"]
  readonly label?: Endpoint8_3Request["payload"]["label"]
}
const Endpoint8_3 = (raw: RawClient["server.integration"]) => (input: Endpoint8_3Input) =>
  raw["integration.connect.oauth"]({
    params: { integrationID: input["integrationID"] },
    query: { location: input["location"] },
    payload: { methodID: input["methodID"], inputs: input["inputs"], label: input["label"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint8_4Request = Parameters<RawClient["server.integration"]["integration.attempt.status"]>[0]
type Endpoint8_4Input = {
  readonly attemptID: Endpoint8_4Request["params"]["attemptID"]
  readonly location?: Endpoint8_4Request["query"]["location"]
}
const Endpoint8_4 = (raw: RawClient["server.integration"]) => (input: Endpoint8_4Input) =>
  raw["integration.attempt.status"]({
    params: { attemptID: input["attemptID"] },
    query: { location: input["location"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint8_5Request = Parameters<RawClient["server.integration"]["integration.attempt.complete"]>[0]
type Endpoint8_5Input = {
  readonly attemptID: Endpoint8_5Request["params"]["attemptID"]
  readonly location?: Endpoint8_5Request["query"]["location"]
  readonly code?: Endpoint8_5Request["payload"]["code"]
}
const Endpoint8_5 = (raw: RawClient["server.integration"]) => (input: Endpoint8_5Input) =>
  raw["integration.attempt.complete"]({
    params: { attemptID: input["attemptID"] },
    query: { location: input["location"] },
    payload: { code: input["code"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint8_6Request = Parameters<RawClient["server.integration"]["integration.attempt.cancel"]>[0]
type Endpoint8_6Input = {
  readonly attemptID: Endpoint8_6Request["params"]["attemptID"]
  readonly location?: Endpoint8_6Request["query"]["location"]
}
const Endpoint8_6 = (raw: RawClient["server.integration"]) => (input: Endpoint8_6Input) =>
  raw["integration.attempt.cancel"]({
    params: { attemptID: input["attemptID"] },
    query: { location: input["location"] },
  }).pipe(Effect.mapError(mapClientError))

const adaptGroup8 = (raw: RawClient["server.integration"]) => ({
  list: Endpoint8_0(raw),
  get: Endpoint8_1(raw),
  connectKey: Endpoint8_2(raw),
  connectOauth: Endpoint8_3(raw),
  attemptStatus: Endpoint8_4(raw),
  attemptComplete: Endpoint8_5(raw),
  attemptCancel: Endpoint8_6(raw),
})

type Endpoint9_0Request = Parameters<RawClient["server.credential"]["credential.update"]>[0]
type Endpoint9_0Input = {
  readonly credentialID: Endpoint9_0Request["params"]["credentialID"]
  readonly location?: Endpoint9_0Request["query"]["location"]
  readonly label: Endpoint9_0Request["payload"]["label"]
}
const Endpoint9_0 = (raw: RawClient["server.credential"]) => (input: Endpoint9_0Input) =>
  raw["credential.update"]({
    params: { credentialID: input["credentialID"] },
    query: { location: input["location"] },
    payload: { label: input["label"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint9_1Request = Parameters<RawClient["server.credential"]["credential.remove"]>[0]
type Endpoint9_1Input = {
  readonly credentialID: Endpoint9_1Request["params"]["credentialID"]
  readonly location?: Endpoint9_1Request["query"]["location"]
}
const Endpoint9_1 = (raw: RawClient["server.credential"]) => (input: Endpoint9_1Input) =>
  raw["credential.remove"]({
    params: { credentialID: input["credentialID"] },
    query: { location: input["location"] },
  }).pipe(Effect.mapError(mapClientError))

const adaptGroup9 = (raw: RawClient["server.credential"]) => ({ update: Endpoint9_0(raw), remove: Endpoint9_1(raw) })

type Endpoint10_0Request = Parameters<RawClient["server.permission"]["permission.request.list"]>[0]
type Endpoint10_0Input = { readonly location?: Endpoint10_0Request["query"]["location"] }
const Endpoint10_0 = (raw: RawClient["server.permission"]) => (input?: Endpoint10_0Input) =>
  raw["permission.request.list"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint10_1Request = Parameters<RawClient["server.permission"]["permission.saved.list"]>[0]
type Endpoint10_1Input = { readonly projectID?: Endpoint10_1Request["query"]["projectID"] }
const Endpoint10_1 = (raw: RawClient["server.permission"]) => (input?: Endpoint10_1Input) =>
  raw["permission.saved.list"]({ query: { projectID: input?.["projectID"] } }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint10_2Request = Parameters<RawClient["server.permission"]["permission.saved.remove"]>[0]
type Endpoint10_2Input = { readonly id: Endpoint10_2Request["params"]["id"] }
const Endpoint10_2 = (raw: RawClient["server.permission"]) => (input: Endpoint10_2Input) =>
  raw["permission.saved.remove"]({ params: { id: input["id"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint10_3Request = Parameters<RawClient["server.permission"]["session.permission.create"]>[0]
type Endpoint10_3Input = {
  readonly sessionID: Endpoint10_3Request["params"]["sessionID"]
  readonly id?: Endpoint10_3Request["payload"]["id"]
  readonly action: Endpoint10_3Request["payload"]["action"]
  readonly resources: Endpoint10_3Request["payload"]["resources"]
  readonly save?: Endpoint10_3Request["payload"]["save"]
  readonly metadata?: Endpoint10_3Request["payload"]["metadata"]
  readonly source?: Endpoint10_3Request["payload"]["source"]
  readonly agent?: Endpoint10_3Request["payload"]["agent"]
}
const Endpoint10_3 = (raw: RawClient["server.permission"]) => (input: Endpoint10_3Input) =>
  raw["session.permission.create"]({
    params: { sessionID: input["sessionID"] },
    payload: {
      id: input["id"],
      action: input["action"],
      resources: input["resources"],
      save: input["save"],
      metadata: input["metadata"],
      source: input["source"],
      agent: input["agent"],
    },
  }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint10_4Request = Parameters<RawClient["server.permission"]["session.permission.list"]>[0]
type Endpoint10_4Input = { readonly sessionID: Endpoint10_4Request["params"]["sessionID"] }
const Endpoint10_4 = (raw: RawClient["server.permission"]) => (input: Endpoint10_4Input) =>
  raw["session.permission.list"]({ params: { sessionID: input["sessionID"] } }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint10_5Request = Parameters<RawClient["server.permission"]["session.permission.get"]>[0]
type Endpoint10_5Input = {
  readonly sessionID: Endpoint10_5Request["params"]["sessionID"]
  readonly requestID: Endpoint10_5Request["params"]["requestID"]
}
const Endpoint10_5 = (raw: RawClient["server.permission"]) => (input: Endpoint10_5Input) =>
  raw["session.permission.get"]({ params: { sessionID: input["sessionID"], requestID: input["requestID"] } }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint10_6Request = Parameters<RawClient["server.permission"]["session.permission.reply"]>[0]
type Endpoint10_6Input = {
  readonly sessionID: Endpoint10_6Request["params"]["sessionID"]
  readonly requestID: Endpoint10_6Request["params"]["requestID"]
  readonly reply: Endpoint10_6Request["payload"]["reply"]
  readonly message?: Endpoint10_6Request["payload"]["message"]
}
const Endpoint10_6 = (raw: RawClient["server.permission"]) => (input: Endpoint10_6Input) =>
  raw["session.permission.reply"]({
    params: { sessionID: input["sessionID"], requestID: input["requestID"] },
    payload: { reply: input["reply"], message: input["message"] },
  }).pipe(Effect.mapError(mapClientError))

const adaptGroup10 = (raw: RawClient["server.permission"]) => ({
  listRequests: Endpoint10_0(raw),
  listSaved: Endpoint10_1(raw),
  removeSaved: Endpoint10_2(raw),
  create: Endpoint10_3(raw),
  list: Endpoint10_4(raw),
  get: Endpoint10_5(raw),
  reply: Endpoint10_6(raw),
})

type Endpoint11_0Request = Parameters<RawClient["server.fs"]["fs.read"]>[0]
type Endpoint11_0Input = {
  readonly location?: Endpoint11_0Request["query"]["location"]
  readonly path: Endpoint11_0Request["query"]["path"]
}
const Endpoint11_0 = (raw: RawClient["server.fs"]) => (input: Endpoint11_0Input) =>
  raw["fs.read"]({ query: { location: input["location"], path: input["path"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint11_1Request = Parameters<RawClient["server.fs"]["fs.list"]>[0]
type Endpoint11_1Input = {
  readonly location?: Endpoint11_1Request["query"]["location"]
  readonly path?: Endpoint11_1Request["query"]["path"]
}
const Endpoint11_1 = (raw: RawClient["server.fs"]) => (input?: Endpoint11_1Input) =>
  raw["fs.list"]({ query: { location: input?.["location"], path: input?.["path"] } }).pipe(
    Effect.mapError(mapClientError),
  )

type Endpoint11_2Request = Parameters<RawClient["server.fs"]["fs.find"]>[0]
type Endpoint11_2Input = {
  readonly location?: Endpoint11_2Request["query"]["location"]
  readonly query: Endpoint11_2Request["query"]["query"]
  readonly type?: Endpoint11_2Request["query"]["type"]
  readonly limit?: Endpoint11_2Request["query"]["limit"]
}
const Endpoint11_2 = (raw: RawClient["server.fs"]) => (input: Endpoint11_2Input) =>
  raw["fs.find"]({
    query: { location: input["location"], query: input["query"], type: input["type"], limit: input["limit"] },
  }).pipe(Effect.mapError(mapClientError))

const adaptGroup11 = (raw: RawClient["server.fs"]) => ({
  read: Endpoint11_0(raw),
  list: Endpoint11_1(raw),
  find: Endpoint11_2(raw),
})

type Endpoint12_0Request = Parameters<RawClient["server.command"]["command.list"]>[0]
type Endpoint12_0Input = { readonly location?: Endpoint12_0Request["query"]["location"] }
const Endpoint12_0 = (raw: RawClient["server.command"]) => (input?: Endpoint12_0Input) =>
  raw["command.list"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

const adaptGroup12 = (raw: RawClient["server.command"]) => ({ list: Endpoint12_0(raw) })

type Endpoint13_0Request = Parameters<RawClient["server.skill"]["skill.list"]>[0]
type Endpoint13_0Input = { readonly location?: Endpoint13_0Request["query"]["location"] }
const Endpoint13_0 = (raw: RawClient["server.skill"]) => (input?: Endpoint13_0Input) =>
  raw["skill.list"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

const adaptGroup13 = (raw: RawClient["server.skill"]) => ({ list: Endpoint13_0(raw) })

type Endpoint14_0Request = Parameters<RawClient["server.mcp"]["mcp.status"]>[0]
type Endpoint14_0Input = { readonly location?: Endpoint14_0Request["query"]["location"] }
const Endpoint14_0 = (raw: RawClient["server.mcp"]) => (input?: Endpoint14_0Input) =>
  raw["mcp.status"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint14_1Request = Parameters<RawClient["server.mcp"]["mcp.resources"]>[0]
type Endpoint14_1Input = { readonly location?: Endpoint14_1Request["query"]["location"] }
const Endpoint14_1 = (raw: RawClient["server.mcp"]) => (input?: Endpoint14_1Input) =>
  raw["mcp.resources"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint14_2Request = Parameters<RawClient["server.mcp"]["mcp.connect"]>[0]
type Endpoint14_2Input = {
  readonly name: Endpoint14_2Request["params"]["name"]
  readonly location?: Endpoint14_2Request["query"]["location"]
}
const Endpoint14_2 = (raw: RawClient["server.mcp"]) => (input: Endpoint14_2Input) =>
  raw["mcp.connect"]({ params: { name: input["name"] }, query: { location: input["location"] } }).pipe(
    Effect.mapError(mapClientError),
  )

type Endpoint14_3Request = Parameters<RawClient["server.mcp"]["mcp.disconnect"]>[0]
type Endpoint14_3Input = {
  readonly name: Endpoint14_3Request["params"]["name"]
  readonly location?: Endpoint14_3Request["query"]["location"]
}
const Endpoint14_3 = (raw: RawClient["server.mcp"]) => (input: Endpoint14_3Input) =>
  raw["mcp.disconnect"]({ params: { name: input["name"] }, query: { location: input["location"] } }).pipe(
    Effect.mapError(mapClientError),
  )

const adaptGroup14 = (raw: RawClient["server.mcp"]) => ({
  status: Endpoint14_0(raw),
  resources: Endpoint14_1(raw),
  connect: Endpoint14_2(raw),
  disconnect: Endpoint14_3(raw),
})

type Endpoint15_0Request = Parameters<RawClient["server.lsp"]["lsp.status"]>[0]
type Endpoint15_0Input = { readonly location?: Endpoint15_0Request["query"]["location"] }
const Endpoint15_0 = (raw: RawClient["server.lsp"]) => (input?: Endpoint15_0Input) =>
  raw["lsp.status"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

const adaptGroup15 = (raw: RawClient["server.lsp"]) => ({ status: Endpoint15_0(raw) })

const Endpoint16_0 = (raw: RawClient["server.project"]) => () =>
  raw["project.list"]({}).pipe(Effect.mapError(mapClientError))

type Endpoint16_1Request = Parameters<RawClient["server.project"]["project.initGit"]>[0]
type Endpoint16_1Input = { readonly location?: Endpoint16_1Request["query"]["location"] }
const Endpoint16_1 = (raw: RawClient["server.project"]) => (input?: Endpoint16_1Input) =>
  raw["project.initGit"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint16_2Request = Parameters<RawClient["server.project"]["project.current"]>[0]
type Endpoint16_2Input = { readonly location?: Endpoint16_2Request["query"]["location"] }
const Endpoint16_2 = (raw: RawClient["server.project"]) => (input?: Endpoint16_2Input) =>
  raw["project.current"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint16_3Request = Parameters<RawClient["server.project"]["project.update"]>[0]
type Endpoint16_3Input = {
  readonly projectID: Endpoint16_3Request["params"]["projectID"]
  readonly name?: Endpoint16_3Request["payload"]["name"]
  readonly icon?: Endpoint16_3Request["payload"]["icon"]
  readonly commands?: Endpoint16_3Request["payload"]["commands"]
}
const Endpoint16_3 = (raw: RawClient["server.project"]) => (input: Endpoint16_3Input) =>
  raw["project.update"]({
    params: { projectID: input["projectID"] },
    payload: { name: input["name"], icon: input["icon"], commands: input["commands"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint16_4Request = Parameters<RawClient["server.project"]["project.directories"]>[0]
type Endpoint16_4Input = {
  readonly projectID: Endpoint16_4Request["params"]["projectID"]
  readonly location?: Endpoint16_4Request["query"]["location"]
}
const Endpoint16_4 = (raw: RawClient["server.project"]) => (input: Endpoint16_4Input) =>
  raw["project.directories"]({
    params: { projectID: input["projectID"] },
    query: { location: input["location"] },
  }).pipe(Effect.mapError(mapClientError))

const adaptGroup16 = (raw: RawClient["server.project"]) => ({
  list: Endpoint16_0(raw),
  initGit: Endpoint16_1(raw),
  current: Endpoint16_2(raw),
  update: Endpoint16_3(raw),
  directories: Endpoint16_4(raw),
})

type Endpoint17_0Request = Parameters<RawClient["server.worktree"]["worktree.create"]>[0]
type Endpoint17_0Input = {
  readonly location?: Endpoint17_0Request["query"]["location"]
  readonly name?: Endpoint17_0Request["payload"]["name"]
  readonly startCommand?: Endpoint17_0Request["payload"]["startCommand"]
}
const Endpoint17_0 = (raw: RawClient["server.worktree"]) => (input?: Endpoint17_0Input) =>
  raw["worktree.create"]({
    query: { location: input?.["location"] },
    payload: { name: input?.["name"], startCommand: input?.["startCommand"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint17_1Request = Parameters<RawClient["server.worktree"]["worktree.remove"]>[0]
type Endpoint17_1Input = {
  readonly location?: Endpoint17_1Request["query"]["location"]
  readonly directory: Endpoint17_1Request["payload"]["directory"]
}
const Endpoint17_1 = (raw: RawClient["server.worktree"]) => (input: Endpoint17_1Input) =>
  raw["worktree.remove"]({ query: { location: input["location"] }, payload: { directory: input["directory"] } }).pipe(
    Effect.mapError(mapClientError),
  )

type Endpoint17_2Request = Parameters<RawClient["server.worktree"]["worktree.reset"]>[0]
type Endpoint17_2Input = {
  readonly location?: Endpoint17_2Request["query"]["location"]
  readonly directory: Endpoint17_2Request["payload"]["directory"]
}
const Endpoint17_2 = (raw: RawClient["server.worktree"]) => (input: Endpoint17_2Input) =>
  raw["worktree.reset"]({ query: { location: input["location"] }, payload: { directory: input["directory"] } }).pipe(
    Effect.mapError(mapClientError),
  )

const adaptGroup17 = (raw: RawClient["server.worktree"]) => ({
  create: Endpoint17_0(raw),
  remove: Endpoint17_1(raw),
  reset: Endpoint17_2(raw),
})

const Endpoint18_0 = (raw: RawClient["server.capability"]) => () =>
  raw["capability.get"]({}).pipe(Effect.mapError(mapClientError))

const adaptGroup18 = (raw: RawClient["server.capability"]) => ({ get: Endpoint18_0(raw) })

type Endpoint19_0Request = Parameters<RawClient["server.vcs"]["vcs.get"]>[0]
type Endpoint19_0Input = { readonly location?: Endpoint19_0Request["query"]["location"] }
const Endpoint19_0 = (raw: RawClient["server.vcs"]) => (input?: Endpoint19_0Input) =>
  raw["vcs.get"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint19_1Request = Parameters<RawClient["server.vcs"]["vcs.status"]>[0]
type Endpoint19_1Input = { readonly location?: Endpoint19_1Request["query"]["location"] }
const Endpoint19_1 = (raw: RawClient["server.vcs"]) => (input?: Endpoint19_1Input) =>
  raw["vcs.status"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint19_2Request = Parameters<RawClient["server.vcs"]["vcs.diff"]>[0]
type Endpoint19_2Input = {
  readonly location?: Endpoint19_2Request["query"]["location"]
  readonly mode: Endpoint19_2Request["query"]["mode"]
  readonly context?: Endpoint19_2Request["query"]["context"]
}
const Endpoint19_2 = (raw: RawClient["server.vcs"]) => (input: Endpoint19_2Input) =>
  raw["vcs.diff"]({ query: { location: input["location"], mode: input["mode"], context: input["context"] } }).pipe(
    Effect.mapError(mapClientError),
  )

const adaptGroup19 = (raw: RawClient["server.vcs"]) => ({
  get: Endpoint19_0(raw),
  status: Endpoint19_1(raw),
  diff: Endpoint19_2(raw),
})

type Endpoint20_0Request = Parameters<RawClient["server.formatter"]["formatter.status"]>[0]
type Endpoint20_0Input = { readonly location?: Endpoint20_0Request["query"]["location"] }
const Endpoint20_0 = (raw: RawClient["server.formatter"]) => (input?: Endpoint20_0Input) =>
  raw["formatter.status"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

const adaptGroup20 = (raw: RawClient["server.formatter"]) => ({ status: Endpoint20_0(raw) })

type Endpoint21_0Request = Parameters<RawClient["server.console"]["console.get"]>[0]
type Endpoint21_0Input = { readonly location?: Endpoint21_0Request["query"]["location"] }
const Endpoint21_0 = (raw: RawClient["server.console"]) => (input?: Endpoint21_0Input) =>
  raw["console.get"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint21_1Request = Parameters<RawClient["server.console"]["console.org.list"]>[0]
type Endpoint21_1Input = { readonly location?: Endpoint21_1Request["query"]["location"] }
const Endpoint21_1 = (raw: RawClient["server.console"]) => (input?: Endpoint21_1Input) =>
  raw["console.org.list"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint21_2Request = Parameters<RawClient["server.console"]["console.org.switch"]>[0]
type Endpoint21_2Input = {
  readonly location?: Endpoint21_2Request["query"]["location"]
  readonly accountID: Endpoint21_2Request["payload"]["accountID"]
  readonly orgID: Endpoint21_2Request["payload"]["orgID"]
}
const Endpoint21_2 = (raw: RawClient["server.console"]) => (input: Endpoint21_2Input) =>
  raw["console.org.switch"]({
    query: { location: input["location"] },
    payload: { accountID: input["accountID"], orgID: input["orgID"] },
  }).pipe(Effect.mapError(mapClientError))

const adaptGroup21 = (raw: RawClient["server.console"]) => ({
  get: Endpoint21_0(raw),
  listOrgs: Endpoint21_1(raw),
  switchOrg: Endpoint21_2(raw),
})

type Endpoint22_0Request = Parameters<RawClient["server.config"]["config.get"]>[0]
type Endpoint22_0Input = { readonly location?: Endpoint22_0Request["query"]["location"] }
const Endpoint22_0 = (raw: RawClient["server.config"]) => (input?: Endpoint22_0Input) =>
  raw["config.get"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint22_1Request = Parameters<RawClient["server.config"]["config.update"]>[0]
type Endpoint22_1Input = { readonly config: Endpoint22_1Request["payload"]["config"] }
const Endpoint22_1 = (raw: RawClient["server.config"]) => (input: Endpoint22_1Input) =>
  raw["config.update"]({ payload: { config: input["config"] } }).pipe(Effect.mapError(mapClientError))

const adaptGroup22 = (raw: RawClient["server.config"]) => ({ get: Endpoint22_0(raw), update: Endpoint22_1(raw) })

type Endpoint23_0Request = Parameters<RawClient["server.workspace"]["workspace.adapter.list"]>[0]
type Endpoint23_0Input = { readonly location?: Endpoint23_0Request["query"]["location"] }
const Endpoint23_0 = (raw: RawClient["server.workspace"]) => (input?: Endpoint23_0Input) =>
  raw["workspace.adapter.list"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint23_1Request = Parameters<RawClient["server.workspace"]["workspace.list"]>[0]
type Endpoint23_1Input = { readonly location?: Endpoint23_1Request["query"]["location"] }
const Endpoint23_1 = (raw: RawClient["server.workspace"]) => (input?: Endpoint23_1Input) =>
  raw["workspace.list"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint23_2Request = Parameters<RawClient["server.workspace"]["workspace.create"]>[0]
type Endpoint23_2Input = {
  readonly location?: Endpoint23_2Request["query"]["location"]
  readonly id?: Endpoint23_2Request["payload"]["id"]
  readonly type: Endpoint23_2Request["payload"]["type"]
  readonly branch?: Endpoint23_2Request["payload"]["branch"]
  readonly extra?: Endpoint23_2Request["payload"]["extra"]
}
const Endpoint23_2 = (raw: RawClient["server.workspace"]) => (input: Endpoint23_2Input) =>
  raw["workspace.create"]({
    query: { location: input["location"] },
    payload: { id: input["id"], type: input["type"], branch: input["branch"], extra: input["extra"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint23_3Request = Parameters<RawClient["server.workspace"]["workspace.remove"]>[0]
type Endpoint23_3Input = {
  readonly workspaceID: Endpoint23_3Request["params"]["workspaceID"]
  readonly location?: Endpoint23_3Request["query"]["location"]
}
const Endpoint23_3 = (raw: RawClient["server.workspace"]) => (input: Endpoint23_3Input) =>
  raw["workspace.remove"]({
    params: { workspaceID: input["workspaceID"] },
    query: { location: input["location"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint23_4Request = Parameters<RawClient["server.workspace"]["workspace.status"]>[0]
type Endpoint23_4Input = { readonly location?: Endpoint23_4Request["query"]["location"] }
const Endpoint23_4 = (raw: RawClient["server.workspace"]) => (input?: Endpoint23_4Input) =>
  raw["workspace.status"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint23_5Request = Parameters<RawClient["server.workspace"]["workspace.syncList"]>[0]
type Endpoint23_5Input = { readonly location?: Endpoint23_5Request["query"]["location"] }
const Endpoint23_5 = (raw: RawClient["server.workspace"]) => (input?: Endpoint23_5Input) =>
  raw["workspace.syncList"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint23_6Request = Parameters<RawClient["server.workspace"]["workspace.start"]>[0]
type Endpoint23_6Input = { readonly location?: Endpoint23_6Request["query"]["location"] }
const Endpoint23_6 = (raw: RawClient["server.workspace"]) => (input?: Endpoint23_6Input) =>
  raw["workspace.start"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint23_7Request = Parameters<RawClient["server.workspace"]["workspace.warp"]>[0]
type Endpoint23_7Input = {
  readonly location?: Endpoint23_7Request["query"]["location"]
  readonly workspaceID: Endpoint23_7Request["payload"]["workspaceID"]
  readonly sessionID: Endpoint23_7Request["payload"]["sessionID"]
  readonly copyChanges?: Endpoint23_7Request["payload"]["copyChanges"]
}
const Endpoint23_7 = (raw: RawClient["server.workspace"]) => (input: Endpoint23_7Input) =>
  raw["workspace.warp"]({
    query: { location: input["location"] },
    payload: { workspaceID: input["workspaceID"], sessionID: input["sessionID"], copyChanges: input["copyChanges"] },
  }).pipe(Effect.mapError(mapClientError))

const adaptGroup23 = (raw: RawClient["server.workspace"]) => ({
  listAdapters: Endpoint23_0(raw),
  list: Endpoint23_1(raw),
  create: Endpoint23_2(raw),
  remove: Endpoint23_3(raw),
  status: Endpoint23_4(raw),
  syncList: Endpoint23_5(raw),
  start: Endpoint23_6(raw),
  warp: Endpoint23_7(raw),
})

type Endpoint24_0Request = Parameters<RawClient["server.controlPlane"]["controlPlane.moveSession"]>[0]
type Endpoint24_0Input = {
  readonly sessionID: Endpoint24_0Request["payload"]["sessionID"]
  readonly destination: Endpoint24_0Request["payload"]["destination"]
  readonly moveChanges?: Endpoint24_0Request["payload"]["moveChanges"]
}
const Endpoint24_0 = (raw: RawClient["server.controlPlane"]) => (input: Endpoint24_0Input) =>
  raw["controlPlane.moveSession"]({
    payload: { sessionID: input["sessionID"], destination: input["destination"], moveChanges: input["moveChanges"] },
  }).pipe(Effect.mapError(mapClientError))

const adaptGroup24 = (raw: RawClient["server.controlPlane"]) => ({ moveSession: Endpoint24_0(raw) })

const Endpoint25_0 = (raw: RawClient["server.plugins"]) => () =>
  raw["plugins.list"]({}).pipe(Effect.mapError(mapClientError))

type Endpoint25_1Request = Parameters<RawClient["server.plugins"]["plugins.marketplace.add"]>[0]
type Endpoint25_1Input = { readonly source: Endpoint25_1Request["payload"]["source"] }
const Endpoint25_1 = (raw: RawClient["server.plugins"]) => (input: Endpoint25_1Input) =>
  raw["plugins.marketplace.add"]({ payload: { source: input["source"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint25_2Request = Parameters<RawClient["server.plugins"]["plugins.marketplace.refresh"]>[0]
type Endpoint25_2Input = { readonly name: Endpoint25_2Request["payload"]["name"] }
const Endpoint25_2 = (raw: RawClient["server.plugins"]) => (input: Endpoint25_2Input) =>
  raw["plugins.marketplace.refresh"]({ payload: { name: input["name"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint25_3Request = Parameters<RawClient["server.plugins"]["plugins.marketplace.remove"]>[0]
type Endpoint25_3Input = { readonly name: Endpoint25_3Request["payload"]["name"] }
const Endpoint25_3 = (raw: RawClient["server.plugins"]) => (input: Endpoint25_3Input) =>
  raw["plugins.marketplace.remove"]({ payload: { name: input["name"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint25_4Request = Parameters<RawClient["server.plugins"]["plugins.install"]>[0]
type Endpoint25_4Input = { readonly id: Endpoint25_4Request["payload"]["id"] }
const Endpoint25_4 = (raw: RawClient["server.plugins"]) => (input: Endpoint25_4Input) =>
  raw["plugins.install"]({ payload: { id: input["id"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint25_5Request = Parameters<RawClient["server.plugins"]["plugins.uninstall"]>[0]
type Endpoint25_5Input = { readonly id: Endpoint25_5Request["payload"]["id"] }
const Endpoint25_5 = (raw: RawClient["server.plugins"]) => (input: Endpoint25_5Input) =>
  raw["plugins.uninstall"]({ payload: { id: input["id"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint25_6Request = Parameters<RawClient["server.plugins"]["plugins.enable"]>[0]
type Endpoint25_6Input = { readonly id: Endpoint25_6Request["payload"]["id"] }
const Endpoint25_6 = (raw: RawClient["server.plugins"]) => (input: Endpoint25_6Input) =>
  raw["plugins.enable"]({ payload: { id: input["id"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint25_7Request = Parameters<RawClient["server.plugins"]["plugins.disable"]>[0]
type Endpoint25_7Input = { readonly id: Endpoint25_7Request["payload"]["id"] }
const Endpoint25_7 = (raw: RawClient["server.plugins"]) => (input: Endpoint25_7Input) =>
  raw["plugins.disable"]({ payload: { id: input["id"] } }).pipe(Effect.mapError(mapClientError))

const adaptGroup25 = (raw: RawClient["server.plugins"]) => ({
  list: Endpoint25_0(raw),
  add: Endpoint25_1(raw),
  refresh: Endpoint25_2(raw),
  remove: Endpoint25_3(raw),
  install: Endpoint25_4(raw),
  uninstall: Endpoint25_5(raw),
  enable: Endpoint25_6(raw),
  disable: Endpoint25_7(raw),
})

const Endpoint26_0 = (raw: RawClient["server.event"]) => () =>
  Stream.unwrap(
    raw["event.subscribe"]({}).pipe(
      Effect.mapError(mapClientError),
      Effect.map((stream) => stream.pipe(Stream.mapError(mapClientError))),
    ),
  )

const adaptGroup26 = (raw: RawClient["server.event"]) => ({ subscribe: Endpoint26_0(raw) })

type Endpoint27_0Request = Parameters<RawClient["server.pty"]["pty.shells"]>[0]
type Endpoint27_0Input = { readonly location?: Endpoint27_0Request["query"]["location"] }
const Endpoint27_0 = (raw: RawClient["server.pty"]) => (input?: Endpoint27_0Input) =>
  raw["pty.shells"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint27_1Request = Parameters<RawClient["server.pty"]["pty.list"]>[0]
type Endpoint27_1Input = { readonly location?: Endpoint27_1Request["query"]["location"] }
const Endpoint27_1 = (raw: RawClient["server.pty"]) => (input?: Endpoint27_1Input) =>
  raw["pty.list"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint27_2Request = Parameters<RawClient["server.pty"]["pty.create"]>[0]
type Endpoint27_2Input = {
  readonly location?: Endpoint27_2Request["query"]["location"]
  readonly command?: Endpoint27_2Request["payload"]["command"]
  readonly args?: Endpoint27_2Request["payload"]["args"]
  readonly cwd?: Endpoint27_2Request["payload"]["cwd"]
  readonly title?: Endpoint27_2Request["payload"]["title"]
  readonly env?: Endpoint27_2Request["payload"]["env"]
}
const Endpoint27_2 = (raw: RawClient["server.pty"]) => (input?: Endpoint27_2Input) =>
  raw["pty.create"]({
    query: { location: input?.["location"] },
    payload: {
      command: input?.["command"],
      args: input?.["args"],
      cwd: input?.["cwd"],
      title: input?.["title"],
      env: input?.["env"],
    },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint27_3Request = Parameters<RawClient["server.pty"]["pty.get"]>[0]
type Endpoint27_3Input = {
  readonly ptyID: Endpoint27_3Request["params"]["ptyID"]
  readonly location?: Endpoint27_3Request["query"]["location"]
}
const Endpoint27_3 = (raw: RawClient["server.pty"]) => (input: Endpoint27_3Input) =>
  raw["pty.get"]({ params: { ptyID: input["ptyID"] }, query: { location: input["location"] } }).pipe(
    Effect.mapError(mapClientError),
  )

type Endpoint27_4Request = Parameters<RawClient["server.pty"]["pty.update"]>[0]
type Endpoint27_4Input = {
  readonly ptyID: Endpoint27_4Request["params"]["ptyID"]
  readonly location?: Endpoint27_4Request["query"]["location"]
  readonly title?: Endpoint27_4Request["payload"]["title"]
  readonly size?: Endpoint27_4Request["payload"]["size"]
}
const Endpoint27_4 = (raw: RawClient["server.pty"]) => (input: Endpoint27_4Input) =>
  raw["pty.update"]({
    params: { ptyID: input["ptyID"] },
    query: { location: input["location"] },
    payload: { title: input["title"], size: input["size"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint27_5Request = Parameters<RawClient["server.pty"]["pty.remove"]>[0]
type Endpoint27_5Input = {
  readonly ptyID: Endpoint27_5Request["params"]["ptyID"]
  readonly location?: Endpoint27_5Request["query"]["location"]
}
const Endpoint27_5 = (raw: RawClient["server.pty"]) => (input: Endpoint27_5Input) =>
  raw["pty.remove"]({ params: { ptyID: input["ptyID"] }, query: { location: input["location"] } }).pipe(
    Effect.mapError(mapClientError),
  )

const adaptGroup27 = (raw: RawClient["server.pty"]) => ({
  shells: Endpoint27_0(raw),
  list: Endpoint27_1(raw),
  create: Endpoint27_2(raw),
  get: Endpoint27_3(raw),
  update: Endpoint27_4(raw),
  remove: Endpoint27_5(raw),
})

type Endpoint28_0Request = Parameters<RawClient["server.question"]["question.request.list"]>[0]
type Endpoint28_0Input = { readonly location?: Endpoint28_0Request["query"]["location"] }
const Endpoint28_0 = (raw: RawClient["server.question"]) => (input?: Endpoint28_0Input) =>
  raw["question.request.list"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint28_1Request = Parameters<RawClient["server.question"]["session.question.list"]>[0]
type Endpoint28_1Input = { readonly sessionID: Endpoint28_1Request["params"]["sessionID"] }
const Endpoint28_1 = (raw: RawClient["server.question"]) => (input: Endpoint28_1Input) =>
  raw["session.question.list"]({ params: { sessionID: input["sessionID"] } }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint28_2Request = Parameters<RawClient["server.question"]["session.question.reply"]>[0]
type Endpoint28_2Input = {
  readonly sessionID: Endpoint28_2Request["params"]["sessionID"]
  readonly requestID: Endpoint28_2Request["params"]["requestID"]
  readonly answers: Endpoint28_2Request["payload"]["answers"]
}
const Endpoint28_2 = (raw: RawClient["server.question"]) => (input: Endpoint28_2Input) =>
  raw["session.question.reply"]({
    params: { sessionID: input["sessionID"], requestID: input["requestID"] },
    payload: { answers: input["answers"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint28_3Request = Parameters<RawClient["server.question"]["session.question.reject"]>[0]
type Endpoint28_3Input = {
  readonly sessionID: Endpoint28_3Request["params"]["sessionID"]
  readonly requestID: Endpoint28_3Request["params"]["requestID"]
}
const Endpoint28_3 = (raw: RawClient["server.question"]) => (input: Endpoint28_3Input) =>
  raw["session.question.reject"]({ params: { sessionID: input["sessionID"], requestID: input["requestID"] } }).pipe(
    Effect.mapError(mapClientError),
  )

const adaptGroup28 = (raw: RawClient["server.question"]) => ({
  listRequests: Endpoint28_0(raw),
  list: Endpoint28_1(raw),
  reply: Endpoint28_2(raw),
  reject: Endpoint28_3(raw),
})

type Endpoint29_0Request = Parameters<RawClient["server.reference"]["reference.list"]>[0]
type Endpoint29_0Input = { readonly location?: Endpoint29_0Request["query"]["location"] }
const Endpoint29_0 = (raw: RawClient["server.reference"]) => (input?: Endpoint29_0Input) =>
  raw["reference.list"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

const adaptGroup29 = (raw: RawClient["server.reference"]) => ({ list: Endpoint29_0(raw) })

type Endpoint30_0Request = Parameters<RawClient["server.projectCopy"]["projectCopy.generateName"]>[0]
type Endpoint30_0Input = {
  readonly projectID: Endpoint30_0Request["params"]["projectID"]
  readonly location?: Endpoint30_0Request["query"]["location"]
  readonly context?: Endpoint30_0Request["payload"]["context"]
}
const Endpoint30_0 = (raw: RawClient["server.projectCopy"]) => (input: Endpoint30_0Input) =>
  raw["projectCopy.generateName"]({
    params: { projectID: input["projectID"] },
    query: { location: input["location"] },
    payload: { context: input["context"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint30_1Request = Parameters<RawClient["server.projectCopy"]["projectCopy.create"]>[0]
type Endpoint30_1Input = {
  readonly projectID: Endpoint30_1Request["params"]["projectID"]
  readonly location?: Endpoint30_1Request["query"]["location"]
  readonly strategy: Endpoint30_1Request["payload"]["strategy"]
  readonly directory: Endpoint30_1Request["payload"]["directory"]
  readonly name?: Endpoint30_1Request["payload"]["name"]
}
const Endpoint30_1 = (raw: RawClient["server.projectCopy"]) => (input: Endpoint30_1Input) =>
  raw["projectCopy.create"]({
    params: { projectID: input["projectID"] },
    query: { location: input["location"] },
    payload: { strategy: input["strategy"], directory: input["directory"], name: input["name"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint30_2Request = Parameters<RawClient["server.projectCopy"]["projectCopy.remove"]>[0]
type Endpoint30_2Input = {
  readonly projectID: Endpoint30_2Request["params"]["projectID"]
  readonly location?: Endpoint30_2Request["query"]["location"]
  readonly directory: Endpoint30_2Request["payload"]["directory"]
  readonly force: Endpoint30_2Request["payload"]["force"]
}
const Endpoint30_2 = (raw: RawClient["server.projectCopy"]) => (input: Endpoint30_2Input) =>
  raw["projectCopy.remove"]({
    params: { projectID: input["projectID"] },
    query: { location: input["location"] },
    payload: { directory: input["directory"], force: input["force"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint30_3Request = Parameters<RawClient["server.projectCopy"]["projectCopy.refresh"]>[0]
type Endpoint30_3Input = {
  readonly projectID: Endpoint30_3Request["params"]["projectID"]
  readonly location?: Endpoint30_3Request["query"]["location"]
}
const Endpoint30_3 = (raw: RawClient["server.projectCopy"]) => (input: Endpoint30_3Input) =>
  raw["projectCopy.refresh"]({
    params: { projectID: input["projectID"] },
    query: { location: input["location"] },
  }).pipe(Effect.mapError(mapClientError))

const adaptGroup30 = (raw: RawClient["server.projectCopy"]) => ({
  generateName: Endpoint30_0(raw),
  create: Endpoint30_1(raw),
  remove: Endpoint30_2(raw),
  refresh: Endpoint30_3(raw),
})

const adaptClient = (raw: RawClient) => ({
  health: adaptGroup0(raw["server.health"]),
  location: adaptGroup1(raw["server.location"]),
  path: adaptGroup2(raw["server.path"]),
  agents: adaptGroup3(raw["server.agent"]),
  sessions: adaptGroup4(raw["server.session"]),
  messages: adaptGroup5(raw["server.message"]),
  models: adaptGroup6(raw["server.model"]),
  providers: adaptGroup7(raw["server.provider"]),
  integrations: adaptGroup8(raw["server.integration"]),
  credentials: adaptGroup9(raw["server.credential"]),
  permissions: adaptGroup10(raw["server.permission"]),
  files: adaptGroup11(raw["server.fs"]),
  commands: adaptGroup12(raw["server.command"]),
  skills: adaptGroup13(raw["server.skill"]),
  mcps: adaptGroup14(raw["server.mcp"]),
  lsp: adaptGroup15(raw["server.lsp"]),
  projects: adaptGroup16(raw["server.project"]),
  worktrees: adaptGroup17(raw["server.worktree"]),
  capabilities: adaptGroup18(raw["server.capability"]),
  vcs: adaptGroup19(raw["server.vcs"]),
  formatters: adaptGroup20(raw["server.formatter"]),
  console: adaptGroup21(raw["server.console"]),
  config: adaptGroup22(raw["server.config"]),
  workspaces: adaptGroup23(raw["server.workspace"]),
  controlPlane: adaptGroup24(raw["server.controlPlane"]),
  "server.plugins": adaptGroup25(raw["server.plugins"]),
  events: adaptGroup26(raw["server.event"]),
  ptys: adaptGroup27(raw["server.pty"]),
  questions: adaptGroup28(raw["server.question"]),
  references: adaptGroup29(raw["server.reference"]),
  projectCopies: adaptGroup30(raw["server.projectCopy"]),
})

export const make = (options?: { readonly baseUrl?: URL | string }) =>
  HttpApiClient.make(ClientApi, options).pipe(Effect.map(adaptClient))
